services:
  - type: web
    name: mutuelle-core
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mutuelle_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mutuelle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health-check/
    autoDeploy: true

databases:
  - name: mutuelle-db
    databaseName: mutuelle_db
    user: mutuelle_user
    plan: free