services:
  - type: web
    name: mutuelle-django
    env: python
    region: frankfurt
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mutuelle_core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DJANGO_SETTINGS_MODULE
        value: mutuelle_core.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"